CREATE TABLE Pizzas 
(
	PizzaId SMALLINT IDENTITY(1,1) NOT NULL,
	PizzaName VARCHAR(20) NOT NULL,
	Ingredients VARCHAR(255) NOT NULL,
	Price SMALLINT NOT NULL,
	ImgName VARCHAR(80) NULL,
	CONSTRAINT UQ_Pizzas_PizzaName UNIQUE (PizzaName),
	CONSTRAINT PK_Pizzas PRIMARY KEY (PizzaId)
)
GO

CREATE TABLE Stages
(
	StageId TINYINT IDENTITY(1,1) NOT NULL,
	StageName VARCHAR(30) NOT NULL
	CONSTRAINT PK_Stages_StageId PRIMARY KEY (StageId)
)
GO
CREATE TABLE Orders
(
	OrderId INT IDENTITY(1,1) NOT NULL,
	CustomerName VARCHAR(50) NOT NULL,
	Telephone VARCHAR(11) NOT NULL,
	DeliveryAddress VARCHAR(80) NOT NULL,
	TotalCost INT NOT NULL,
	DateOfPurchase SMALLDATETIME DEFAULT(CURRENT_TIMESTAMP),
	StageId TINYINT DEFAULT(1)
	CONSTRAINT PK_Orders_OrderId PRIMARY KEY CLUSTERED (OrderId DESC),
)
GO

CREATE TABLE PizzasInCart 
(
	PizzaInCartId INT IDENTITY(1,1) NOT NULL,
	OrderId INT NULL,
	PizzaId INT NOT NULL,
	Amount TINYINT DEFAULT(0)
	CONSTRAINT PK_PizzasInCart_PizzaInCartId PRIMARY KEY (PizzaInCartId)
	CONSTRAINT FK_PizzasInCart_OrderId FOREIGN KEY (OrderId) REFERENCES Orders(OrderId) ON DELETE CASCADE
)
GO



